In [2]:
import pandas as pd

In [8]:
df = pd.read_csv("daily_trading_report/2023-05-05-AccountStatement.csv")

In [15]:
pd.set_option('display.max_columns', None)  # or 1000
pd.set_option('display.max_rows', None)  # or 1000
pd.set_option('display.max_colwidth', None)  # or 199

,DATE,TIME,TYPE,REF #,DESCRIPTION,Misc Fees,Commissions & Fees,AMOUNT,BALANCE
0,5/4/23,22:47:22,TRD,1671897725,BOT +100 MCB @18.96,NaN,NaN,"-1,896.00","98,298.04"
1,5/4/23,22:51:48,TRD,1671906135,BOT +100 NRDY @2.94,NaN,NaN,-294.00,"98,004.04"
2,5/4/23,22:52:47,TRD,1671897774,SOLD -100 MCB @19.70,-0.03,NaN,"1,970.00","99,974.01"
3,5/4/23,22:56:12,TRD,1671906161,SOLD -100 NRDY @2.92,-0.01,NaN,292.00,"100,266.00"
4,5/4/23,22:56:30,TRD,1671913770,BOT +100 ACGN @2.53,NaN,NaN,-253.00,"100,013.00"
5,5/4/23,22:58:19,TRD,1671916763,BOT +100 WAL @18.05,NaN,NaN,"-1,805.00","98,208.00"
6,5/4/23,22:59:07,TRD,1671916790,"BOT +1,000 ASNS @5.88",NaN,NaN,"-5,880.00","92,328.00"
7,5/4/23,23:00:47,TRD,1671919771,"BOT +1,000 PACW @3.02",NaN,NaN,"-3,020.00","89,308.00"
8,5/4/23,23:01:07,TRD,1671919780,"SOLD -1,000 PACW @3.07",-0.05,NaN,"3,070.00","92,377.95"
9,5/4/23,23:02:29,TRD,1671922834,"BOT +1,000 PACW @3.11",NaN,NaN,"-3,110.00","89,267.95"
10,5/4/23,23:03:12,TRD,1671913777,SOLD -100 ACGN @2.52,-0.01,NaN,252.00,"89,519.94"
11,5/4/23,23:05:14,TRD,1671926529,BOT +100 ZION @20.99,NaN,NaN,"-2,099.00","87,420.94"
12,5/4/23,23:06:09,TRD,1671916796,"SOLD -1,000 ASNS @6.28",-0.11,NaN,"6,280.00","93,700.83"
13,5/4/23,23:06:51,TRD,1671922843,"SOLD -1,000 PACW @3.18",-0.05,NaN,"3,180.00","96,880.78"
14,5/4/23,23:12:24,TRD,1671939436,"BOT +1,000 GFAI @7.77",NaN,NaN,"-7,770.00","89,110.78"
15,5/4/23,23:14:10,TRD,1671926537,SOLD -100 ZION @20.98,-0.04,NaN,"2,098.00","91,208.74"
16,5/4/23,23:15:07,TRD,1671942692,"BOT +1,000 MINM @3.75",NaN,NaN,"-3,750.00","87,458.74"
17,5/4/23,23:15:30,TRD,1671945201,"SOLD -1,000 MINM @3.65",-0.06,NaN,"3,650.00","91,108.68"
18,5/4/23,23:15:30,TRD,1671939448,"SOLD -1,000 GFAI @7.65",-0.13,NaN,"7,650.00","98,758.55"
19,5/4/23,23:16:04,TRD,1671945252,"BOT +1,000 ASNS @8.19",NaN,NaN,"-8,190.00","90,568.55"
20,5/4/23,23:24:55,TRD,1671955769,"BOT +1,000 HCDI @6.18",NaN,NaN,"-6,180.00","84,388.55"
21,5/4/23,23:26:14,TRD,1671955780,"SOLD -1,000 HCDI @6.17",-0.10,NaN,"6,170.00","90,558.45"
22,5/4/23,23:26:16,TRD,1671945274,"SOLD -1,000 ASNS @7.50",-0.13,NaN,"7,500.00","98,058.32"
23,5/4/23,23:27:00,TRD,1671958257,"BOT +1,000 HCDI @6.17",NaN,NaN,"-6,170.00","91,888.32"
24,5/4/23,23:36:13,TRD,1671969720,"BOT +1,000 GFAI @7.68",NaN,NaN,"-7,680.00","84,208.32"
25,5/4/23,23:36:33,TRD,1671958272,"SOLD -1,000 HCDI @6.22",-0.11,NaN,"6,220.00","90,428.21"
26,5/4/23,23:37:35,TRD,1671969741,"SOLD -1,000 GFAI @7.78",-0.13,NaN,"7,780.00","98,208.08"
27,5/4/23,23:38:41,TRD,1671916764,SOLD -100 WAL @19.42,-0.03,NaN,"1,942.00","100,150.05"
28,5/4/23,23:41:23,TRD,1671975422,"BOT +1,000 HCDI @6.25",NaN,NaN,"-6,250.00","93,900.05"
29,5/4/23,23:44:01,TRD,1671975430,"SOLD -1,000 HCDI @6.24",-0.11,NaN,"6,240.00","100,139.94"
30,5/4/23,23:55:35,TRD,1671990660,"BOT +1,000 SNTG @3.72",NaN,NaN,"-3,720.00","96,419.94"
31,5/4/23,23:57:11,TRD,1671992535,BOT +100 CUEN @4.71,NaN,NaN,-471.00,"95,948.94"
32,5/5/23,00:06:09,TRD,1672000578,"BOT +10,000 EQ @.5651",NaN,NaN,"-5,651.00","90,297.94"
33,5/5/23,00:13:23,TRD,1672009204,BOT +100 MGIH @1.92,NaN,NaN,-192.00,"90,105.94"
34,5/5/23,00:18:04,TRD,1672014109,"BOT +1,000 TQQQ @26.63",NaN,NaN,"-26,630.00","63,475.94"
35,5/5/23,00:23:33,TRD,1672018473,BOT +100 LICN @2.54,NaN,NaN,-254.00,"63,221.94"
36,5/5/23,00:33:35,TRD,1672030317,BOT +100 TOP @35.84,NaN,NaN,"-3,584.00","59,637.94"
37,5/5/23,00:35:39,TRD,1672030338,SOLD -100 TOP @37.76,-0.06,NaN,"3,776.00","63,413.88"
38,5/5/23,00:36:48,TRD,1672032342,"BOT +1,000 USDP @1.79",NaN,NaN,"-1,790.00","61,623.88"
39,5/5/23,00:39:13,TRD,1672034925,"BOT +1,000 AMTX @1.61",NaN,NaN,"-1,610.00","60,013.88"
40,5/5/23,00:41:17,TRD,1672034969,"SOLD -1,000 TQQQ @26.71",-0.45,NaN,"26,710.00","86,723.43"
41,5/5/23,00:42:13,TRD,1672018488,SOLD -100 LICN @2.46,-0.01,NaN,246.00,"86,969.42"
42,5/5/23,00:45:00,TRD,1672032352,"SOLD -1,000 USDP @1.77",-0.03,NaN,"1,770.00","88,739.39"
43,5/5/23,00:45:32,TRD,1672034933,"SOLD -1,000 AMTX @1.70",-0.03,NaN,"1,700.00","90,439.36"
44,5/5/23,00:52:46,TRD,1672043184,"BOT +10,000 AMBO @.2616",NaN,NaN,"-2,616.00","87,823.36"
45,5/5/23,00:54:07,TRD,1672046722,"BOT +1,000 MGI @10.92",NaN,NaN,"-10,920.00","76,903.36"
46,5/5/23,00:56:37,TRD,1672046786,"BOT +10,000 CNTB @1.22",NaN,NaN,"-12,200.00","64,703.36"
47,5/5/23,00:57:51,TRD,1672050416,"BOT +1,000 BLBX @2.95",NaN,NaN,"-2,950.00","61,753.36"
48,5/5/23,00:57:59,TRD,1672009220,SOLD -100 MGIH @1.74,-0.01,NaN,174.00,"61,927.35"
49,5/5/23,00:58:59,TRD,1672050446,"BOT +1,000 MGRX @1.16",NaN,NaN,"-1,160.00","60,767.35"
50,5/5/23,01:00:30,TRD,1672053907,BOT +500 ACXP @2.87,NaN,NaN,"-1,435.00","59,332.35"
51,5/5/23,01:01:57,TRD,1671990674,"SOLD -1,000 SNTG @3.59",-0.06,NaN,"3,590.00","62,922.29"
52,5/5/23,01:03:38,TRD,1672046791,"SOLD -10,000 CNTB @1.21",-0.20,NaN,"12,100.00","75,022.09"
53,5/5/23,01:05:35,TRD,1672050455,"SOLD -1,000 MGRX @1.15",-0.02,NaN,"1,150.00","76,172.07"
54,5/5/23,01:19:58,TRD,1672068294,"BOT +10,000 CRKN @.1362",NaN,NaN,"-1,362.00","74,810.07"
55,5/5/23,01:24:08,TRD,1672050427,"SOLD -1,000 BLBX @2.94",-0.05,NaN,"2,940.00","77,750.02"
56,5/5/23,01:25:12,TRD,1672072205,"SOLD -10,000 CRKN @.1314",-0.02,NaN,"1,314.00","79,064.00"
57,5/5/23,01:40:42,TRD,1672090650,"BOT +10,000 KSPN @.67",NaN,NaN,"-6,700.00","72,364.00"
58,5/5/23,01:43:38,TRD,1672090669,"SOLD -10,000 KSPN @.67",-0.11,NaN,"6,700.00","79,063.89"
59,5/5/23,01:44:23,TRD,1672093969,"BOT +1,000 TQQQ @26.91",NaN,NaN,"-26,910.00","52,153.89"
60,5/5/23,02:39:41,TRD,1672043200,"SOLD -10,000 AMBO @.2699",-0.05,NaN,"2,699.00","54,852.84"
61,5/5/23,03:29:16,TRD,1671992546,SOLD -100 CUEN @5.09,-0.01,NaN,509.00,"55,361.83"
62,5/5/23,03:46:20,TRD,1672002407,"SOLD -10,000 EQ @.54",-0.09,NaN,"5,400.00","60,761.74"
63,5/5/23,03:49:52,TRD,1672053915,SOLD -500 ACXP @2.88,-0.02,NaN,"1,440.00","62,201.72"